name = "Survive and Thrive"
author = "Rhythmic System"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e45bc253e9bdc552108cecca27e7246b70e4a8176f45ebde1f2d995ebd51537f"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"
