name = "Survive and Thrive"
author = "Rhythmic System"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ae0b62f9d599efd7cbbd6c5ce290677e260170c55005e85fc723c3644613491"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"
