name = "Survive and Thrive"
author = "Rhythmic System"
version = "0.0.6-server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b8173f6ca8efb1a9f9ab3dc36237966360afe5540c7bceecb44b945e8802c9e"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"
