name = "Survive and Thrive"
author = "Rhythmic System"
version = "0.0.9-singleplayer"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2fb371e646d74a4ee9e512c2c509c906a593e93e8045aa56f086e2907e4b985"

[versions]
forge = "47.1.0"
minecraft = "1.20.1"
